### ISSUE TITLE
Implement DID resolution

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/tbdex-kt#14]
Used by crypto

**Comment by phoebe-lew** [comment]
@andresuribe87 On the TS side we had implemented this functionality: https://github.com/TBD54566975/tbdex-js/blob/main/packages/protocol/src/did-resolver.ts

But if it's already in scope for `web5-sdk-kotlin`, very happy to just pull it in.

**Comment by andresuribe87** [comment]
Thanks @phoebe-lew 

I looked at the implementation and I see that it's a thin wrapper on top of existing resolvers that are maintains in web5-js

I'm not sure what the requirements are, so I can't make a concrete recommendation. That said, my initial suggestion would be to use the universal resolver. That gives you the fastest way to support resolution for as many did methods as you'd like. The downside is that you'll need to run the resolver. I don't think that's a big deal, since you are already relying on some ion instance to be running (I think MSFTs?) in order to do ion resolution.

**Comment by phoebe-lew** [comment]
we'll be able to pull this in from `web5.DidResolvers`
